{
    "name": "POS Community IoT",
    "summary": "Bridge Point of Sale printing to Community IoT devices.",
    "description": "Send POS receipt and preparation print jobs to Community IoT devices.",
    "version": "18.0.1.0.0",
    "category": "Point of Sale",
    "author": "JDA SOLUTIONS",
    "maintainer": "JDA SOLUTIONS",
    "website": "https://github.com/julesprog963-stack/pos_community_iot",
    "support": "julesprog963@gmail.com",
    "license": "LGPL-3",
    "price": 0.0,
    "currency": "USD",
    "images": [
        "static/description/main_screenshot.png",
        "static/description/images/pos_configuration_odoo18.png",
        "static/description/images/pos_copies_folios_odoo18.png",
        "static/description/images/pos_iot_printer_odoo18.png",
        "static/description/images/pos_operation_odoo18.png",
    ],
    "depends": ["point_of_sale", "community_iot_box"],
    "data": [
        "views/res_config_settings_views.xml",
        "views/pos_printer_views.xml",
    ],
    "assets": {
        "point_of_sale._assets_pos": [
            "pos_community_iot/static/src/css/receipt_iot.css",
            "pos_community_iot/static/src/js/receipt_iot_common.js",
            "pos_community_iot/static/src/js/receipt_iot_patch.js",
            "pos_community_iot/static/src/js/preparation_iot_patch.js",
        ],
    },
    "installable": True,
    "application": False,
}
